ALTER TABLE users
  ADD COLUMN IF NOT EXISTS job_title VARCHAR(120),
  ADD COLUMN IF NOT EXISTS timezone VARCHAR(80),
  ADD COLUMN IF NOT EXISTS bio TEXT;

ALTER TABLE workspaces
  ADD COLUMN IF NOT EXISTS guest_access BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS require_2fa BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS public_templates BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE user_preferences
  ADD COLUMN IF NOT EXISTS density VARCHAR(16) NOT NULL DEFAULT 'comfortable',
  ADD COLUMN IF NOT EXISTS accent VARCHAR(16) NOT NULL DEFAULT 'ocean',
  ADD COLUMN IF NOT EXISTS reduce_motion BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notify_mentions BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_assignments BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_due_dates BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_files BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notify_digest BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS two_factor BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS login_alerts BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS slack BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS github BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS figma BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS google_drive BOOLEAN NOT NULL DEFAULT FALSE;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'user_preferences_density_check'
  ) THEN
    ALTER TABLE user_preferences
      ADD CONSTRAINT user_preferences_density_check
      CHECK (density IN ('comfortable', 'compact'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'user_preferences_accent_check'
  ) THEN
    ALTER TABLE user_preferences
      ADD CONSTRAINT user_preferences_accent_check
      CHECK (accent IN ('ocean', 'teal', 'aqua', 'emerald', 'amber'));
  END IF;
END $$;
